export default [
  { id: 1, name: "fist", icon: "item/weapon/fist", atk: 4, price: 0 },
  {
    id: 2,
    name: "dagger",
    icon: "item/weapon/plain-dagger",
    atk: 10,
    price: 40,
  },
  {
    id: 3,
    name: "sword",
    icon: "item/weapon/sword-brandish",
    atk: 16,
    price: 90,
  },
  {
    id: 4,
    name: "broadsword",
    icon: "item/weapon/broadsword",
    atk: 20,
    price: 200,
  },
  {
    id: 5,
    name: "stiletto",
    icon: "item/weapon/stiletto",
    atk: 25,
    price: 300,
  },
  {
    id: 6,
    name: "huge axe",
    icon: "item/weapon/sharp-axe",
    atk: 33,
    price: 500,
  },
  { id: 7, name: "katana", icon: "item/weapon/katana", atk: 40, price: 600 },
  ,
  { id: 8, name: "machete", icon: "item/weapon/machete", atk: 44, price: 800 },
  ,
  {
    id: 9,
    name: "two sabres",
    icon: "item/weapon/crossed-sabres",
    atk: 50,
    price: 1000,
  },
  ,
  {
    id: 10,
    name: "great hammer",
    icon: "item/weapon/thor-hammer",
    atk: 54,
    price: 1200,
  },
];
