<template>
  <div>
    <!--
    <div class="who-turn">
      <p v-if="$store.state.isMyTurn">my turn</p>
      <p v-else>enemy turn</p>
    </div>
    -->
    <div
      :class="`battle half-width ${battleAnimation}`"
      @animationend="resetAnimations()"
      v-if="$store.state.player.hp > 0"
    >
      <div>
        <Enemy class="item3 half-width" v-if="this.$store.state.currentEnemy" />
        <Loot class="item3 half-width" v-if="this.$store.state.currentLoot" />
        <button
          v-if="this.$store.state.currentEnemy"
          class="button half-width attack-button"
          @click="onAttackButton()"
          :disabled="!canAttack"
        >attack</button>
        <BattleLog class="item4" />
        <QuestionModal />
      </div>
      <div v-if="this.$store.state.previousAnswer">
        <div class="half-width" v-if="this.$store.state.currentLoot">
          <button
            @click="$store.commit('collectLoot')"
            class="button collect-loot half-width"
          >collect loot</button>
        </div>
      </div>
    </div>

    <div v-else>
      <p class="game-over">game over</p>
      <p>you dead buddy</p>

      <button class="button reset-button" @click="$store.commit('reset')">start again!</button>
    </div>
  </div>
</template>

<script>
import Enemy from "./Enemy";
import Loot from "./Loot";
import BattleLog from "./BattleLog";
import QuestionModal from "./QuestionModal";

export default {
  name: "Battle",
  props: {
    msg: String,
  },
  components: {
    Enemy,
    BattleLog,
    Loot,
    QuestionModal,
  },
  methods: {
    resetAnimations() {
      let a = this.$store.state.animation;
      a.playerHit = false;
      a.playerDodge = false;
    },
    onAttackButton() {
      this.$store.commit("onAttackButton");
    },
  },
  computed: {
    canAttack: function () {
      return !this.$store.state.blockClick;
    },
    player: function () {
      return this.$store.state.player;
    },
    isShowQuestion: function () {
      return this.$store.state.isMyTurn;
    },
    battleAnimation: function () {
      return "";
      /*
      if (this.$store.state.animation.playerHit) {
        return "shake-horizontal";
      }
      if (this.$store.state.animation.playerDodge) return ""; //todo player dodge animation. i tried to add but its bugged
      return "";
      */
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.game-over {
  font-size: 3rem;
  margin: 1rem;
}
.reset-button {
  margin: 2rem;
}
.who-turn {
  margin: 0.5rem;
}
.attack-button {
  margin: 1rem 0 1rem 0;
}
.battle {
  margin: auto;

  display: grid;
}
@media screen and (min-width: 800px) {
  .battle-grid {
    grid-template-columns: 50% 50%;
  }
}

@media screen and (max-width: 800px) {
  .battle-grid {
    grid-template-columns: 100%;
  }
}

.collect-loot {
  margin-top: 1rem;
  width: 300px;
  height: 100px;
}

@media screen and (max-width: 800px) {
  .collect-loot {
    margin-top: 0.5rem;
    height: 2.5rem;
  }
}

.shake-horizontal {
  -webkit-animation: shake-horizontal 0.8s
    cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
  animation: shake-horizontal 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

.slide-out-left {
  -webkit-animation: slide-out-left 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53)
    both;
  animation: slide-out-left 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-8-28 15:28:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}
@keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2020-8-30 20:53:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
  50% {
    -webkit-transform: translateX(-300px);
    transform: translateX(-300px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-out-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
  50% {
    -webkit-transform: translateX(-300px);
    transform: translateX(-300px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
</style>
