<template>
  <div class="battle-log half-width">
    <div v-for="(item, i) in log" :key="i">
      <p v-if="item.isRead" class="read">{{ item.content }}</p>
      <div
        v-else
        :class="`unread ${animationClass}`"
        @animationend="animationTrigger = false"
      >
        <div v-if="item.color">
          <p :style="`color:${item.color}`">{{ item.content }}</p>
        </div>
        <p v-else>{{ item.content }}</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "BattleLog",
  props: {
    msg: String,
  },
  data: function() {
    return {
      animationTrigger: false,
    };
  },
  computed: {
    animationClass: function() {
      if (this.animationTrigger) return "scale-up-ver-center";
      return "";
    },
    log: function() {
      let all = [...this.$store.state.gameLog];
      all.reverse();
      return all.slice(0, 5);
    },
  },
  watch: {
    log: function() {
      this.animationTrigger = true;
    },
  },
};
</script>
<style scoped>
.battle-log {
  font-size: 0.7rem;
  margin-top: 1rem;
}

.unread {
  font-size: 1rem;
}
.read {
  display: none;
}

@media screen and (max-width: 800px) {
  .unread {
    font-size: 0.8rem;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2020-8-28 15:18:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-ver-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-ver-center {
  0% {
    -webkit-transform: scaleY(0.4);
    transform: scaleY(0.4);
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
  }
}
@keyframes scale-up-ver-center {
  0% {
    -webkit-transform: scaleY(0.4);
    transform: scaleY(0.4);
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
  }
}

.scale-up-ver-center {
  -webkit-animation: scale-up-ver-center 0.4s
    cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-ver-center 0.4s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
</style>
