<template>
  <div>
    <div
      :class="`battle-grid full-width ${battleAnimation}`"
      @animationend="resetAnimations()"
      v-if="$store.state.player.hp>0"
    >
      <div>
        <Enemy class="item3 half-width" v-if="this.$store.state.currentEnemy" />
        <Loot class="item3 half-width" v-if="this.$store.state.currentLoot" />
        <BattleLog class="item4" />
      </div>
      <div v-if="this.$store.state.previousAnswer">
        <Question class="item1 half-width" />
        <SelectAnswer class="item2 half-width" />
        <div class="half-width" v-if="this.$store.state.currentLoot">
          <button
            @click="$store.commit('collectLoot')"
            class="button collect-loot half-width"
          >collect loot</button>
        </div>
      </div>
    </div>

    <div v-else>
      <p>you dead buddy</p>
    </div>
  </div>
</template>

<script>
import Enemy from "./Enemy";
import Loot from "./Loot";
import Question from "./Question";
import SelectAnswer from "./SelectAnswer";
import BattleLog from "./BattleLog";

export default {
  name: "Battle",
  props: {
    msg: String,
  },
  components: {
    Enemy,
    SelectAnswer,
    BattleLog,
    Question,
    Loot,
  },
  methods: {
    resetAnimations() {
      let a = this.$store.state.animation;
      a.playerHit = false;
      a.playerDodge = false;
    },
  },
  computed: {
    battleAnimation: function () {
      if (this.$store.state.animation.playerHit) {
        return "shake-horizontal";
      }
      if (this.$store.state.animation.playerDodge) return ""; //todo player dodge animation. i tried to add but its bugged
      return "";
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.battle-grid {
  margin: auto;

  display: grid;

  grid-gap: 2 px;

  grid-template-columns: 50% 50%;
  grid-template-rows: auto;
}
.collect-loot {
  margin-top: 1rem;
  width: 300px;
  height: 100px;
}

.shake-horizontal {
  -webkit-animation: shake-horizontal 0.8s
    cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
  animation: shake-horizontal 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

.slide-out-left {
  -webkit-animation: slide-out-left 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53)
    both;
  animation: slide-out-left 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-8-28 15:28:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}
@keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2020-8-30 20:53:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
  50% {
    -webkit-transform: translateX(-300px);
    transform: translateX(-300px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-out-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
  50% {
    -webkit-transform: translateX(-300px);
    transform: translateX(-300px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
</style>
