<template>
  <b-navbar>
    <template slot="brand"></template>
    <template slot="start">
      <b-navbar-item>
        <p
          :class="levelClass"
          @animationend="$store.state.animation.levelUp=false"
        >level: {{player.level}}</p>
      </b-navbar-item>
      <b-navbar-item>
        <b-progress
          type="is-info"
          :max="player.nextLevelExp"
          :value="player.exp"
          :show-value="true"
        >exp: {{player.exp}}/{{player.nextLevelExp}}</b-progress>
      </b-navbar-item>
      <b-navbar-item>
        gold:
        {{player.gold}}
      </b-navbar-item>
      <b-navbar-item>
        <b-progress
          type="is-success"
          :max="player.maxHp"
          :value=" player.hp"
          :show-value="true"
        >hp: {{player.hp}}/{{player.maxHp}}</b-progress>
      </b-navbar-item>
    </template>

    <template slot="end">
      <b-navbar-item
        :active="$store.state.currentScene=='battle'"
        @click="$store.state.currentScene='battle'"
      >battle</b-navbar-item>
      <b-navbar-item
        :active="$store.state.currentScene=='shop'"
        @click="$store.state.currentScene='shop'"
      >shop</b-navbar-item>
      <b-navbar-item
        :active="$store.state.currentScene=='inventory'"
        @click="$store.state.currentScene='inventory'"
      >inventory</b-navbar-item>
      <b-navbar-item
        :active="$store.state.currentScene=='locations'"
        @click="$store.state.currentScene='locations'"
      >locations</b-navbar-item>
    </template>
  </b-navbar>
</template>

<script>
export default {
  components: {},
  data() {
    return {};
  },
  computed: {
    player: function () {
      return this.$store.state.player;
    },
    levelClass: function () {
      if (this.$store.state.animation.levelUp) return "pulsate-bck level"; //on level up animation
      return "level";
    },
  },
};
</script>
<style scoped>
.game-menu {
  text-align: left;
}
.level {
}
.pulsate-bck {
  -webkit-animation: pulsate-bck 0.5s ease-in-out 2 both;
  animation: pulsate-bck 0.5s ease-in-out 2 both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-8-30 20:17:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-bck
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(1.5);
    transform: scale(1.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(1.5);
    transform: scale(1.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
