<template>
  <b-navbar>
    <template slot="brand">
      <!--only mobile-->
      <b-navbar-item class="is-hidden-desktop display-font player-level"
        >level {{ player.level }}</b-navbar-item
      >
      <b-navbar-item class="is-hidden-desktop display-font"
        >gold: {{ player.gold }}</b-navbar-item
      >
      <b-navbar-item>
        <b-progress
          class="progress-bar player-exp"
          type="is-info"
          :max="player.nextLevelExp - player.minExp"
          :value="player.exp - player.minExp"
          :show-value="true"
          >exp: {{ player.exp }}/{{ player.nextLevelExp }}</b-progress
        >
      </b-navbar-item>
    </template>
    <template slot="start">
      <b-navbar-item class="is-hidden-touch display-font player-level">
        <p
          :class="levelClass"
          @animationend="$store.state.animation.levelUp = false"
        >
          level {{ player.level }}
        </p>
      </b-navbar-item>

      <b-navbar-item class="is-hidden-touch display-font">
        gold:
        {{ player.gold }}
      </b-navbar-item>
      <!--
      <b-navbar-item class="is-hidden-touch">
        <b-progress
          type="is-success"
          :max="player.maxHp"
          :value="player.hp"
          :show-value="true"
        >hp: {{ player.hp }}/{{ player.maxHp }}</b-progress>
      </b-navbar-item>
      -->
    </template>

    <template slot="end">
      <b-navbar-item
        :active="currentScene == 'battle'"
        @click="changeScene('battle')"
        >battle</b-navbar-item
      >

      <b-navbar-item
        :active="currentScene == 'shop'"
        @click="changeScene('shop')"
        >shop</b-navbar-item
      >
      <b-navbar-item
        :active="currentScene == 'locations'"
        @click="changeScene('locations')"
        >locations</b-navbar-item
      >

      <b-navbar-dropdown label="More...">
        <b-navbar-item
          :active="currentScene == 'inventory'"
          @click="changeScene('inventory')"
          >inventory</b-navbar-item
        >

        <b-navbar-item
          :active="currentScene == 'cardlist'"
          @click="changeScene('cardlist')"
          >vocabulary list</b-navbar-item
        >
        <!--
        <b-navbar-item
          :active="currentScene == 'achievements'"
          @click="changeScene('achievements')"
        >achievements</b-navbar-item>
        -->
        <!--
        <b-navbar-item
          :active="currentScene == 'journal'"
          @click="changeScene('journal')"
          >journal</b-navbar-item
        >
        <b-navbar-item
          :active="currentScene == 'town'"
          @click="changeScene('town')"
          >town</b-navbar-item
        >-->
        <b-navbar-item
          :active="currentScene == 'debug'"
          @click="changeScene('debug')"
          >settings</b-navbar-item
        >
      </b-navbar-dropdown>
      <b-navbar-item>practiced: {{ $store.state.reviewsCount }}</b-navbar-item>
      <b-navbar-item class="version">v{{ $store.state.version }}</b-navbar-item>
    </template>
  </b-navbar>
</template>

<script>
export default {
  components: {},
  data() {
    return {};
  },
  computed: {
    player: function() {
      return this.$store.state.player;
    },
    levelClass: function() {
      if (this.$store.state.animation.levelUp) return "pulsate-bck level"; //on level up animation
      return "level";
    },
    currentScene: function() {
      return this.$store.state.currentScene;
    },
  },
  methods: {
    changeScene: function(sceneName) {
      this.$store.state.currentScene = sceneName;
    },
  },
};
</script>
<style scoped>
.game-menu {
  text-align: left;
}
.version {
  color: grey;
}
.player-level {
  font-size: 1rem;
}
.player-exp {
  width: 100px;
}
.pulsate-bck {
  -webkit-animation: pulsate-bck 0.5s ease-in-out 2 both;
  animation: pulsate-bck 0.5s ease-in-out 2 both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-8-30 20:17:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-bck
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(1.5);
    transform: scale(1.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(1.5);
    transform: scale(1.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
