<template>
  <section>
    <b-modal
      v-model="isShow"
      has-modal-card
      trap-focus
      :destroy-on-hide="false"
      aria-role="dialog"
      aria-modal
    >
      <div class="modal-card question-modal">
        <header class="modal-card-head">
          <p class="modal-card-title">select correct answer</p>

          <button
            v-if="isShowAnswer"
            class="delete is-large"
            aria-label="close"
            @click="$store.commit('closeQuestionModal')"
          ></button>
        </header>
        <section class="modal-card-body">
          <Question />
          <SelectAnswer />
          <br />
          <div v-if="isShowAnswer">
            <b-icon
              v-if="$store.state.previousAnswer.wasCorrect"
              class="correct-answer answer rotate-center"
              icon="smile"
              size="is-large"
            ></b-icon>
            <b-icon
              v-else
              class="wrong-answer answer shake-bottom"
              icon="frown"
              size="is-large"
            ></b-icon>
          </div>
          <div v-else>
            <div class="wait-for-answer"></div>
          </div>
        </section>
      </div>
    </b-modal>
  </section>
</template>

<script>
import Question from "./Question";
import SelectAnswer from "./SelectAnswer";

export default {
  components: {
    Question,
    SelectAnswer,
  },
  computed: {
    isShowAnswer: function() {
      return this.$store.state.isShowAnswer;
    },
    isShow: function() {
      return this.$store.state.isShowQuestionModal;
    },
  },
  data() {
    return {
      isComponentModalActive: false,
    };
  },
};
</script>
<style scoped>
.close-button {
  margin: 2rem;
}
.question-modal {
  border-radius: 10px;
}
.correct-answer {
  color: rgb(46, 88, 46);
}
.wrong-answer {
  color: rgb(175, 29, 34);
}
.answer {
  font-size: 2rem;
}
.wait-for-answer {
  margin: 3rem;
}
.tip {
  margin-top: 1rem;
  font-size: 0.8rem;
}

.rotate-center {
  -webkit-animation: rotate-center 0.6s ease-in-out both;
  animation: rotate-center 0.6s ease-in-out both;
}
.shake-bottom {
  -webkit-animation: shake-bottom 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955)
    both;
  animation: shake-bottom 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-9-17 16:11:43
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
@-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2020-9-17 16:13:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-vertical
 * ----------------------------------------
 */
@-webkit-keyframes shake-vertical {
  0%,
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateY(8px);
    transform: translateY(8px);
  }
  80% {
    -webkit-transform: translateY(6.4px);
    transform: translateY(6.4px);
  }
  90% {
    -webkit-transform: translateY(-6.4px);
    transform: translateY(-6.4px);
  }
} /* ----------------------------------------------
 * Generated by Animista on 2020-9-17 16:15:12
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-bottom
 * ----------------------------------------
 */
@-webkit-keyframes shake-bottom {
  0%,
  100% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
  }
  10% {
    -webkit-transform: rotate(2deg);
    transform: rotate(2deg);
  }
  20%,
  40%,
  60% {
    -webkit-transform: rotate(-4deg);
    transform: rotate(-4deg);
  }
  30%,
  50%,
  70% {
    -webkit-transform: rotate(4deg);
    transform: rotate(4deg);
  }
  80% {
    -webkit-transform: rotate(-2deg);
    transform: rotate(-2deg);
  }
  90% {
    -webkit-transform: rotate(2deg);
    transform: rotate(2deg);
  }
}
@keyframes shake-bottom {
  0%,
  100% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
  }
  10% {
    -webkit-transform: rotate(2deg);
    transform: rotate(2deg);
  }
  20%,
  40%,
  60% {
    -webkit-transform: rotate(-4deg);
    transform: rotate(-4deg);
  }
  30%,
  50%,
  70% {
    -webkit-transform: rotate(4deg);
    transform: rotate(4deg);
  }
  80% {
    -webkit-transform: rotate(-2deg);
    transform: rotate(-2deg);
  }
  90% {
    -webkit-transform: rotate(2deg);
    transform: rotate(2deg);
  }
}
</style>
