<template>
  <div id="app" :class="animation" @animationend="$store.state.animation.playerHit=false">
    <div v-if="$store.state.cards">
      <TopInfo />
      <div class="columns">
        <div class="column is-one-quarter">
          <Menu />
        </div>
        <div class="column">
          <Battle v-if="currentScene=='battle'" />
          <Shop v-if="currentScene == 'shop'" />
          <Inventory v-if="currentScene == 'inventory'" />
          <Locations v-if="currentScene=='locations'" />
        </div>
      </div>
      <hr />
      <div class="debug-wrapper">
        <DebugPanel v-if="$store.state.isDebug" />
      </div>
      <div class="debug-wrapper">
        <b-checkbox v-model="$store.state.isDebug">show debug panel</b-checkbox>
      </div>
    </div>
    <div v-else>
      <SelectDeck />
    </div>
  </div>
</template>

<script>
import TopInfo from "./components/TopInfo";
import Battle from "./components/Battle";
import Shop from "./components/Shop";
import Inventory from "./components/Inventory";
import DebugPanel from "./components/DebugPanel";
import Locations from "./components/Locations";
import Menu from "./components/Menu";
import SelectDeck from "./components/SelectDeck";

export default {
  name: "App",
  components: {
    TopInfo,
    Battle,
    Shop,
    Inventory,
    DebugPanel,
    Locations,
    Menu,
    SelectDeck,
  },
  computed: {
    currentScene: function () {
      return this.$store.state.currentScene;
    },
    animation: function () {
      if (this.$store.state.animation.playerHit) {
        return "shake-horizontal";
      }
      return "";
    },
  },
  mounted: function () {},
};
</script>

<style>
@import url("https://fonts.googleapis.com/css2?family=Quicksand&display=swap");

#app {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  font-family: "Quicksand", sans-serif;
}
.navigation-button {
  margin: 1rem;
}
.debug-wrapper {
  margin: 1rem;
  text-align: right;
}

.shake-horizontal {
  -webkit-animation: shake-horizontal 0.8s
    cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
  animation: shake-horizontal 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-8-28 15:28:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}
@keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}
</style>
