//todo load masterdata from csv

//define parameters here
export default {
  exp: [
    {
      level: 1,
      exp: 0,
    },
    {
      level: 2,
      exp: 15,
    },
    {
      level: 3,
      exp: 30,
    },
    {
      level: 4,
      exp: 60,
    },
    {
      level: 5,
      exp: 100,
    },
    {
      level: 6,
      exp: 130,
    },
    {
      level: 7,
      exp: 170,
    },
    {
      level: 8,
      exp: 210,
    },
    {
      level: 9,
      exp: 240,
    },
    {
      level: 10,
      exp: 300,
    },
    {
      level: 11,
      exp: 350,
    },
    {
      level: 12,
      exp: 400,
    },
    {
      level: 13,
      exp: 460,
    },
    {
      level: 14,
      exp: 520,
    },
    {
      level: 15,
      exp: 580,
    },
    {
      level: 16,
      exp: 670,
    },
    {
      level: 17,
      exp: 790,
    },
    {
      level: 18,
      exp: 890,
    },
    {
      level: 19,
      exp: 1000,
    },
    {
      level: 20,
      exp: 1110,
    },
    {
      level: 21,
      exp: 1230,
    },
  ],
  parameters: [
    { level: 1, hp: 20 },
    { level: 2, hp: 25 },
    { level: 3, hp: 35 },
    { level: 4, hp: 45 },
    { level: 5, hp: 60 },
    { level: 6, hp: 70 },
    { level: 7, hp: 80 },
    { level: 8, hp: 90 },
    { level: 9, hp: 105 },
    { level: 10, hp: 115 },
    { level: 11, hp: 130 },
    { level: 12, hp: 140 },
    { level: 13, hp: 160 },
    { level: 14, hp: 180 },
    { level: 15, hp: 200 },
    { level: 16, hp: 210 },
    { level: 17, hp: 230 },
    { level: 18, hp: 250 },
    { level: 19, hp: 270 },
    { level: 20, hp: 290 },
    { level: 21, hp: 310 },
  ],
  locations: [
    {
      id: 1,
      order: 1,
      name: "forest",
      icon: "forest",
      enemies: [1, 2, 3],
      unlockConditions: [],
    },
    {
      id: 901,
      order: 2,
      name: "forest: boss stage",
      icon: "witch-face",
      enemies: [901],
      unlockConditions: [{ level: 4 }],
    },
    {
      id: 2,
      order: 3,
      name: "cementary",
      icon: "tombstone",
      requiredLevel: 6,
      enemies: [4, 5, 6],
      unlockConditions: [{ kill: 901 }],
    },
    {
      id: 902,
      name: "cementary: boss stage",
      icon: "skull-slices",
      enemies: [902],
      unlockConditions: [{ level: 9 }, { location: 2 }],
    },
    {
      id: 3,
      order: 4,
      name: "hell",
      icon: "flaming-trident",
      enemies: [7, 8, 9],
      unlockConditions: [{ level: 11 }, { kill: 902 }],
    },
    {
      id: 903,
      order: 5,
      name: "hell: boss stage",
      icon: "diablo-skull",
      enemies: [903],
      unlockConditions: [{ level: 14 }, { location: 3 }],
    },
    {
      id: 4,
      order: 6,
      name: "vampire castle",
      icon: "castle-ruins",
      enemies: [10, 11, 12],
      unlockConditions: [{ level: 16 }, { kill: 903 }],
    },
    {
      id: 904,
      order: 7,
      name: "vampire castle: boss stage",
      icon: "vampire-dracula",

      requiredLevel: 19,
      enemies: [904],
      unlockConditions: [{ level: 19 }, { location: 4 }],
    },
  ],
  //each enemy definition
  enemies: [
    {
      id: 1,
      atk: 1,
      hp: 7,
      name: "bad gnome",
      image: "bad-gnome",
      exp: 5,
      loot: [{ type: "gold", amount: 5 }],
    },
    {
      id: 2,
      atk: 2,
      hp: 9,
      name: "slime",
      image: "transparent-slime",
      exp: 6,
      loot: [{ type: "gold", amount: 8 }],
    },
    {
      id: 3,
      atk: 3,
      hp: 12,
      name: "tree",
      image: "tree-face",
      exp: 7,
      loot: [{ type: "gold", amount: 12 }],
    },

    {
      id: 4,
      atk: 5,
      hp: 20,
      name: "ghost",
      image: "ghost",
      exp: 8,
      loot: [{ type: "gold", amount: 15 }],
    },
    {
      id: 5,
      atk: 6,
      hp: 25,
      name: "spectre",
      image: "spectre",
      exp: 9,
      loot: [{ type: "gold", amount: 18 }],
    },
    {
      id: 6,
      atk: 7,
      hp: 25,
      name: "mummy",
      image: "mummy-head",
      exp: 10,
      loot: [{ type: "gold", amount: 22 }],
    },
    {
      id: 7,
      atk: 9,
      hp: 25,
      name: "gooey demon",
      image: "gooey-daemon",
      exp: 11,
      loot: [{ type: "gold", amount: 22 }],
    },
    {
      id: 8,
      atk: 10,
      hp: 25,
      name: "evil fork",
      image: "evil-fork",
      exp: 12,
      loot: [{ type: "gold", amount: 25 }],
    },
    {
      id: 9,
      atk: 11,
      hp: 25,
      name: "imp",
      image: "imp-laugh",
      exp: 13,
      loot: [{ type: "gold", amount: 30 }],
    },
    {
      id: 10,
      atk: 14,
      hp: 30,
      name: "baby bat",
      image: "swamp-bat",
      exp: 13,
      loot: [{ type: "gold", amount: 40 }],
    },
    {
      id: 11,
      atk: 15,
      hp: 35,
      name: "adult bat",
      image: "imp",
      exp: 13,
      loot: [{ type: "gold", amount: 45 }],
    },
    {
      id: 12,
      atk: 16,
      hp: 45,
      name: "baby vampire",
      image: "swallower",
      exp: 13,
      loot: [{ type: "gold", amount: 50 }],
    },
    {
      id: 901,
      atk: 6,
      hp: 50,
      name: "witch",
      image: "witch-face",
      exp: 20,
      loot: [{ type: "gold", amount: 40 }],
    },
    {
      id: 902,
      atk: 15,
      hp: 100,
      name: "skeletor king",
      image: "skull-slices",
      exp: 30,
      loot: [{ type: "gold", amount: 80 }],
    },
    {
      id: 903,
      atk: 22,
      hp: 150,
      name: "demon king",
      image: "diablo-skull",
      exp: 50,
      loot: [{ type: "gold", amount: 110 }],
    },
    {
      id: 904,
      atk: 30,
      hp: 200,
      name: "vampire",
      image: "vampire-dracula",
      exp: 90,
      loot: [{ type: "gold", amount: 180 }],
    },
  ],
  weapons: [
    { id: 1, name: "fist", icon: "weapon/fist", atk: 4, price: 0 },
    { id: 2, name: "dagger", icon: "weapon/plain-dagger", atk: 10, price: 40 },
    { id: 3, name: "sword", icon: "weapon/sword-brandish", atk: 16, price: 90 },
    {
      id: 4,
      name: "broadsword",
      icon: "weapon/broadsword",
      atk: 20,
      price: 200,
    },
    { id: 5, name: "stiletto", icon: "weapon/stiletto", atk: 25, price: 300 },
    { id: 6, name: "huge axe", icon: "weapon/sharp-axe", atk: 33, price: 500 },
    { id: 7, name: "katana", icon: "weapon/katana", atk: 40, price: 600 },
  ],
  armor: [
    { id: 1, name: "shirt", def: 0, price: 0 },
    {
      id: 2,
      name: "leather vest",
      icon: "chest/leather-vest",
      def: 2,
      price: 40,
    },
    {
      id: 3,
      name: "leather armor",
      icon: "chest/leather-armor",
      def: 3,
      price: 90,
    },
    { id: 4, name: "armor vest", icon: "chest/armor-vest", def: 6, price: 200 },
    {
      id: 5,
      name: "breastplate",
      icon: "chest/breastplate",
      def: 8,
      price: 300,
    },
    { id: 6, name: "magic armor", icon: "chest/lamellar", def: 12, price: 500 },
    { id: 7, name: "gold armor", icon: "chest/plastron", def: 20, price: 600 },
  ],
  quest: [
    {
      id: 1,
      name: "small bad boys",
      desc:
        "So sleepy... Those little bastards stole my pillow! I just want my revenge! Help me and I will make you a warrior.",
      conditions: [1],
      rewards: [1],
      requiredLevel: 1,
    },
  ],
  achievements: [
    { id: 1, condition: { type: "kill", enemyId: 1, count: 10 } },
    { id: 2, condition: { type: "kill", enemyId: 2, count: 10 } },
    { id: 3, condition: { type: "kill", enemyId: 3, count: 10 } },
    { id: 4, condition: { type: "kill", enemyId: 4, count: 20 } },
    { id: 5, condition: { type: "kill", enemyId: 5, count: 20 } },
    { id: 6, condition: { type: "kill", enemyId: 6, count: 20 } },
    { id: 7, condition: { type: "kill", enemyId: 7, count: 30 } },
    { id: 8, condition: { type: "gold", amount: 100 } },
  ],

  condition: [
    { id: 1, type: "kill", count: 3, enemyId: 1 },
    { id: 1, type: "kill", count: 3, enemyId: 2 },
  ],
  reward: [{ id: 1, type: "weapon", masterId: 2, amount: 1 }],
  miscItems: [{ name: "small-potion", itemType: "heal", heal: 10 }],
};
